# Generated by Django 4.2.3 on 2023-07-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(max_length=20)),
                ('img', models.ImageField(default=None, upload_to='pics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist_name', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('bild_art', models.CharField(max_length=50)),
                ('bild_standort', models.CharField(max_length=50)),
                ('art_nr', models.CharField(max_length=50)),
                ('Jahrgang', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
